version: "3"

services:
  app:
    build: .
    image: "citizensadvice/mokta"
    ports:
      - 4001:4001
    volumes:
      - .:/app
    environment:
      - URL_HOST=app.test
      - MOKTA_ISSUER=https://cadev.oktapreview.com
      - MOKTA_REDIRECT_URL=http://app.test:3000
